title: Dario Jurčević # your name (or website title) here
logo: "/images/DSC_9387.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Unity Developer & Journalist
  <br><br>
  Get in touch: daarioj@outlook.com or/ dario.jurcevic.dev@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/dario-jur%C4%8Devi%C4%87-750149234/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
